---
spring:
  application:
    name: CarApplication
  output:
    ansi:
      enabled: detect
  profiles:
    active: local,SKIP_SSL_VALIDATION
  mvc:
    view:
      suffix: .html
#server:
  #context-path: /
  #port: 8080
kroger:
  eaf:
    version: 5.1.0
  ldap:
    filter-order: -10
  management:
    security:
      roles: oa--support-0000
      enabled: false
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info,krypt,keepalive
#logging:
  #level:
    #org.springframework.security: DEBUG
---
spring:
  profiles: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    initialization-mode: embedded
kroger:
  oauth:
    default-target-uri: http://localhost:8080
    logout-uri: https://federation.kroger.com/identity/logout
security:
  oauth2:
    client:
      clientId: 3927-ngppui-local
      clientSecret: secret
      accessTokenUri: https://federation.kroger.com/identity/oauth/token
      userAuthorizationUri: https://federation.kroger.com/identity/oauth/authorize
    resource:
      tokenInfoUri: https://federation.kroger.com/identity/oauth/check_token
---
spring:
  profiles: cloud
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    initialization-mode: embedded
    hikari:
      maximum-pool-size: 50
      minimum-idle: 3
      connection-timeout: 30000
kroger:
  oauth:
    default-target-uri: ${vcap.services.-auth.credentials.defaultTargetUri}
    logout-uri: ${vcap.services.-auth.credentials.identityServerUri}/identity/logout
security:
  oauth2:
    client:
      clientId: ${vcap.services.-auth.credentials.clientId}
      clientSecret: ${vcap.services.-auth.credentials.clientSecret}
      accessTokenUri: ${vcap.services.-auth.credentials.identityServerUri}/identity/oauth/token
      userAuthorizationUri: ${vcap.services.-auth.credentials.identityServerUri}/identity/oauth/authorize
    resource:
      tokenInfoUri: ${vcap.services.-auth.credentials.identityServerUri}/identity/oauth/check_token
---
spring:
  profiles: unittest
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    initialization-mode: embedded
kroger:
  oauth:
    default-target-uri: http://localhost:8080
    logout-uri: https://federation.kroger.com/identity/logout
security:
  oauth2:
    client:
      clientId: 0000--local
      clientSecret: secret
      accessTokenUri: https://federation.kroger.com/identity/oauth/token
      userAuthorizationUri: https://federation.kroger.com/identity/oauth/authorize
    resource:
      tokenInfoUri: https://federation.kroger.com/identity/oauth/check_token
