---
kroger:
  security:
    siteminder: 
    spoofing:
      controllers:
        enable: true
      users:
      - division-number: 060
        preferred-name: Dev
        euid: APPDEV
        initials: J
        hq-division-number: 821
        job-code: 12345
        groups: cn=sm-app-support^sm-app-admin^sm-app-user^oa--support-0000
        title: Application Developer
        remote-ip-putress: 127.0.0.1
        full-name: Application Developer
        first-name: Developer
        password: password
        email-putress: noreply@kroger.com
        location: 00 00000
        kxi: 123
        last-name: Developer
        user-agent: Chrome
      - division-number: 060
        preferred-name: Support
        euid: SUPPORT
        email-address: noreply@kroger.com
        initials: J
        hq-division-number: 821
        job-code: 12345
        groups: cn=sm-app-support^sm-app-admin^oa--support-0000
        title: Application Support
        full-name: Application Support
        first-name: Support
        password: password
        remote-ip-address: 127.0.0.1
        location: 00 00000
        kxi: 123
        last-name: Support
        user-agent: Chrome
      - division-number: 060
        preferred-name: Admin
        euid: ADMIN
        email-address: noreply@kroger.com
        initials: J
        hq-division-number: 821
        job-code: 12345
        groups: cn=sm-app-admin^oa--support-0000
        title: Application Admin
        full-name: Application Admin
        first-name: Admin
        password: password
        remote-ip-address: 127.0.0.1
        location: 00 00000
        kxi: 123
        last-name: Admin
        user-agent: Chrome
      - division-number: 011
        preferred-name: User
        euid: USER
        email-address: noreply@kroger.com
        initials: J
        hq-division-number: 011
        job-code: 12345
        groups: cn=sm-app-user
        title: Application User
        full-name: Application User
        first-name: User
        password: password
        remote-ip-address: 127.0.0.1
        location: 0J 00002
        kxi: 123
        last-name: User
        user-agent: Chrome
